allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  bcrypt: set this to true or false
  canvas: set this to true or false
  core-js: set this to true or false
  esbuild: set this to true or false
  prisma: true
  sharp: set this to true or false
