-- Insert Procedures into Production Database
-- Run this against the production database

-- First clear existing procedures
DELETE FROM surgical_procedure_options;

-- Insert procedures (category as text, convert to enum in queries)
INSERT INTO surgical_procedure_options (name, category, is_active, is_billable, default_price, created_at) VALUES
('360HD LASER LIPO', 'BODY_CONTOURING', true, true, 9800, NOW()),
('ABDOMINOPLASTY', 'BODY_CONTOURING', true, true, 88100, NOW()),
('ARM LIFT', 'BODY_CONTOURING', true, true, 82500, NOW()),
('ARM LIPO', 'BODY_CONTOURING', true, true, 68000, NOW()),
('ARMS', 'Procedure', true, true, 23500, NOW()),
('BACK LIPO', 'BODY_CONTOURING', true, true, 65000, NOW()),
('BELLY BUTTON RECONSTRUCTION', 'BODY_CONTOURING', true, true, 15000, NOW()),
('BENCHMARK DIMPLING', 'Procedure', true, true, 2500, NOW()),
('BLEPHAROPLASTY', 'FACE', true, true, 68000, NOW()),
('BODY CONTOURING', 'BODY_CONTOURING', true, true, 150000, NOW()),
('BOTOX', 'NON_SURGICAL', true, true, 28000, NOW()),
('BREAST AUGMENTATION', 'BREAST', true, true, 125000, NOW()),
('BREAST LIFT', 'BREAST', true, true, 95000, NOW()),
('BREAST RECONSTRUCTION', 'RECONSTRUCTIVE', true, true, 150000, NOW()),
('BREAST REDUCTION', 'BREAST', true, true, 95000, NOW()),
('BROW LIFT', 'FACE', true, true, 45000, NOW()),
('BUCCAL FAT REMOVAL', 'FACE', true, true, 35000, NOW()),
('BULK BILLING', 'Procedure', true, true, 0, NOW()),
('BUTT LIPO', 'BODY_CONTOURING', true, true, 75000, NOW()),
('BUTTOCK AUGMENTATION', 'BODY_CONTOURING', true, true, 95000, NOW()),
('CALF AUGMENTATION', 'BODY_CONTOURING', true, true, 75000, NOW()),
('CALF LIPO', 'BODY_CONTOURING', true, true, 55000, NOW()),
('CANTHOPEXY', 'FACE', true, true, 28000, NOW()),
('CHEEK AUGMENTATION', 'FACE', true, true, 45000, NOW()),
('CHEEK LIPO', 'FACE', true, true, 35000, NOW()),
('CHIN AUGMENTATION', 'FACE', true, true, 35000, NOW()),
('CHIN LIPO', 'FACE', true, true, 28000, NOW()),
('CHIN REDUCTION', 'FACE', true, true, 35000, NOW()),
('CONSULTATION', 'Consultation', true, true, 5000, NOW()),
('CONSULTATION - FOLLOW UP', 'Consultation', true, true, 3000, NOW()),
('CORRECTIVE SURGERY', 'Procedure', true, true, 0, NOW()),
('DEEP FACELIFT', 'FACE', true, true, 185000, NOW()),
('DERMABRASION', 'FACE', true, true, 25000, NOW()),
('DIEP FLAP', 'RECONSTRUCTIVE', true, true, 250000, NOW()),
('DIMPLE CREATION', 'FACE', true, true, 15000, NOW()),
('DOUBLE CHIN LIPO', 'FACE', true, true, 28000, NOW()),
('EAR LOBE REPAIR', 'FACE', true, true, 8000, NOW()),
('EAR RECONSTRUCTION', 'RECONSTRUCTIVE', true, true, 45000, NOW()),
('EARPINS', 'FACE', true, true, 25000, NOW()),
('EVLA', 'NON_SURGICAL', true, true, 35000, NOW()),
('EYEBAG REMOVAL', 'FACE', true, true, 38000, NOW()),
('FACE LIFT', 'FACE', true, true, 145000, NOW()),
('FACE/NECK LIFT', 'FACE_AND_NECK', true, true, 165000, NOW()),
('FACELIFT', 'FACE', true, true, 145000, NOW()),
('FAT GRAFTING - BODY', 'BODY_CONTOURING', true, true, 85000, NOW()),
('FAT GRAFTING - BREAST', 'BODY_CONTOURING', true, true, 95000, NOW()),
('FAT GRAFTING - FACE', 'FACE', true, true, 55000, NOW()),
('FAT GRAFTING - HANDS', 'Procedure', true, true, 35000, NOW()),
('FAT GRAFTING - BUTTOCKS', 'BODY_CONTOURING', true, true, 95000, NOW()),
('FILLERS', 'NON_SURGICAL', true, true, 25000, NOW()),
('FOREHEAD LIFT', 'FACE', true, true, 45000, NOW()),
('FULL MOMM MAKEOVER', 'Procedure', true, true, 350000, NOW()),
('GYNECOMASTIA', 'Procedure', true, true, 65000, NOW()),
('HAIR TRANSPLANT', 'HAIR_RESTORATION', true, true, 145000, NOW()),
('HIGH DEF LIPO', 'BODY_CONTOURING', true, true, 145000, NOW()),
('HYMENOPLASTY', 'Procedure', true, true, 35000, NOW()),
('JAW CONTOURING', 'FACE', true, true, 55000, NOW()),
('JAW LIPO', 'FACE', true, true, 45000, NOW()),
('LABIAPLASTY', 'INTIMATE_AESTHETIC', true, true, 45000, NOW()),
('LABIUM MINORA REDUCTION', 'INTIMATE_AESTHETIC', true, true, 45000, NOW()),
('LAPAROSCOPIC ABDOMINOPLASTY', 'BODY_CONTOURING', true, true, 125000, NOW()),
('LARYNX', 'Procedure', true, true, 0, NOW()),
('LASER HAIR REMOVAL', 'NON_SURGICAL', true, true, 25000, NOW()),
('LEGS', 'BODY_CONTOURING', true, true, 85000, NOW()),
('LIFT AFTER WEIGHT LOSS', 'POST_WEIGHT_LOSS', true, true, 145000, NOW()),
('LIPO 360', 'BODY_CONTOURING', true, true, 165000, NOW()),
('LIPO ABROAD', 'BODY_CONTOURING', true, true, 185000, NOW()),
('LIPO AFTER WEIGHT LOSS', 'POST_WEIGHT_LOSS', true, true, 125000, NOW()),
('LIPOSUCTION', 'BODY_CONTOURING', true, true, 85000, NOW()),
('LOWER BACK LIPO', 'BODY_CONTOURING', true, true, 55000, NOW()),
('LOWER BODY LIFT', 'BODY_CONTOURING', true, true, 145000, NOW()),
('MALE BREAST REMOVAL', 'Procedure', true, true, 65000, NOW()),
('MASTOPEXY', 'BREAST', true, true, 85000, NOW()),
('MAYO REPAIR', 'Procedure', true, true, 0, NOW()),
('MDR ULTHERAPY', 'NON_SURGICAL', true, true, 35000, NOW()),
('MENTOPLASTY', 'FACE', true, true, 35000, NOW()),
('MONEY MAKER', 'Procedure', true, true, 2500, NOW()),
('MOMM MAKEOVER', 'Procedure', true, true, 285000, NOW()),
('MOLE REMOVAL', 'Procedure', true, true, 8000, NOW()),
('NECK LIFT', 'FACE_AND_NECK', true, true, 75000, NOW()),
('NECK LIPO', 'FACE_AND_NECK', true, true, 38000, NOW()),
('NIPPLE RECONSTRUCTION', 'RECONSTRUCTIVE', true, true, 25000, NOW()),
('NOSE', 'Procedure', true, true, 0, NOW()),
('NR LIPO', 'FACE', true, true, 45000, NOW()),
('ORECHE', 'Procedure', true, true, 0, NOW()),
('OTOPLASTY', 'FACE', true, true, 45000, NOW()),
('PACKAGE A', 'Procedure', true, true, 250000, NOW()),
('PACKAGE B', 'Procedure', true, true, 350000, NOW()),
('PATIENT CONSULTATION', 'Consultation', true, true, 0, NOW()),
('PECH', 'Procedure', true, true, 0, NOW()),
('PERSISTENT OTORRHAGIA', 'Procedure', true, true, 0, NOW()),
('PLASMA LIPO', 'BODY_CONTOURING', true, true, 145000, NOW()),
('PRP', 'NON_SURGICAL', true, true, 15000, NOW()),
('RADIO FREQUENCY', 'NON_SURGICAL', true, true, 25000, NOW()),
('REPAIR', 'Procedure', true, true, 0, NOW()),
('REVERSE TUMMOR TUCK', 'BODY_CONTOURING', true, true, 95000, NOW()),
('RHINOPLASTY', 'FACE', true, true, 115000, NOW()),
('RIB GRAFTING', 'RECONSTRUCTIVE', true, true, 185000, NOW()),
('SAFELIPO', 'BODY_CONTOURING', true, true, 95000, NOW()),
('SCARS', 'Procedure', true, true, 0, NOW()),
('SCAR REVISION', 'Procedure', true, true, 25000, NOW()),
('SENTINAL NODE BIOPSY', 'Procedure', true, true, 0, NOW()),
('SEXUAL REASSIGNMENT', 'INTIMATE_AESTHETIC', true, true, 250000, NOW()),
('SINUS SURGERY', 'Procedure', true, true, 0, NOW()),
('SKIN GRAFTING', 'RECONSTRUCTIVE', true, true, 45000, NOW()),
('SLEEVING', 'Procedure', true, true, 0, NOW()),
('SOCKET RECONSTRUCTION', 'RECONSTRUCTIVE', true, true, 35000, NOW()),
('SOFT LIPO', 'BODY_CONTOURING', true, true, 95000, NOW()),
('SPIDER VEINS', 'Procedure', true, true, 0, NOW()),
('STOMACH LIPO', 'BODY_CONTOURING', true, true, 55000, NOW()),
('SUBCISION', ' Procedure', true, true, 25000, NOW()),
('SUNKEN CHEEK RECONSTRUCTION', 'FACE', true, true, 35000, NOW()),
('SURGICAL GYNECOMASTIA', 'Procedure', true, true, 75000, NOW()),
('TATTTOO REMOVAL', 'NON_SURGICAL', true, true, 25000, NOW()),
('THIGH LIFT', 'BODY_CONTOURING', true, true, 95000, NOW()),
('THIGH LIPO', 'BODY_CONTOURING', true, true, 68000, NOW()),
('THIGH REDUCTION', 'BODY_CONTOURING', true, true, 65000, NOW()),
('THREE AREOLAS', 'BREAST', true, true, 2500, NOW()),
('TOE AUGMENTATION', 'BODY_CONTOURING', true, true, 25000, NOW()),
('TOE REDUCTION', 'BODY_CONTOURING', true, true, 25000, NOW()),
('TOTAL BODY LIFT', 'POST_WEIGHT_LOSS', true, true, 285000, NOW()),
('TOTAL BODY LIPO', 'BODY_CONTOURING', true, true, 285000, NOW()),
('TRACHEOSTOMY', 'FACE', true, true, 45000, NOW()),
('TUBEROUS BREAST CORRECTION', 'BREAST', true, true, 85000, NOW()),
('TUG', 'BODY_CONTOURING', true, true, 65000, NOW()),
('TUMMOR TUCK', 'BODY_CONTOURING', true, true, 85000, NOW()),
('TUMMY TUCK', 'BODY_CONTOURING', true, true, 85000, NOW()),
('UMBILICOPLASTY', 'BODY_CONTOURING', true, true, 25000, NOW()),
('UPPER ARM LIPO', 'BODY_CONTOURING', true, true, 45000, NOW()),
('UPPER BODY LIFT', 'BODY_CONTOURING', true, true, 125000, NOW()),
('URINAL RECONSTRUCTION', 'Procedure', true, true, 35000, NOW()),
('VAGINOPLASTY', 'INTIMATE_AESTHETIC', true, true, 55000, NOW()),
('VASER', 'BODY_CONTOURING', true, true, 145000, NOW()),
('VASER LIPO', 'BODY_CONTOURING', true, true, 145000, NOW()),
('VASER HI DEF', 'BODY_CONTOURING', true, true, 185000, NOW()),
('VEIN REMOVAL', 'Procedure', true, true, 15000, NOW()),
('VENTRAL HERNIA', 'Procedure', true, true, 0, NOW()),
('VOLUMA', 'NON_SURGICAL', true, true, 85000, NOW()),
('WAIST CONTORING', 'BODY_CONTOURING', true, true, 0, NOW()),
('WAIST绣', 'Procedure', true, true, 0, NOW()),
('WEIGHT LOSS AFTER CARE', 'POST_WEIGHT_LOSS', true, true, 25000, NOW()),
('WIDENING', 'Procedure', true, true, 85000, NOW()),
('WRINKLE REMOVAL', 'NON_SURGICAL', true, true, 25000, NOW()),
('ZIMMA PLLA', 'Procedure', true, true, 0, NOW());

-- Verify count
SELECT COUNT(*) as procedure_count FROM surgical_procedure_options WHERE is_active = true;\PRecho 'Inserted procedures: ' || (SELECT COUNT(*) FROM surgical_procedure_options WHERE is_active = true) || ' procedures now in database.'