-- Inventory items from Excel
DELETE FROM "InventoryItem";

INSERT INTO "InventoryItem" (name, sku, category, "unit_of_measure", "unit_cost", "is_billable", "is_active", "reorder_point", "low_stock_threshold") VALUES
('Angelique Massage Oil 500ml', 'IMPL-ANGEL-500ML', 'IMPLANT', 'bottle', 0, false, true, 0, 0),
('Biretix Hydramat Gel 50ml', 'IMPL-BIRE-50ML', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('Botox Per Unit', 'IMPL-BOTOX-UNIT', 'IMPLANT', 'unit', 450, true, true, 0, 0),
('Endocare Renewal Retinol 30ml', 'IMPL-ENDO-30ML', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('Go Pain Arnica Gel 100g', 'IMPL-ARNICA-100G', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('Heliocare 360 Gel Oil 50ml', 'IMPL-HELIO-GEL-50', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('Heliocare 360 Invisible Spray 200ml', 'IMPL-HELIO-SPRY-200', 'IMPLANT', 'bottle', 0, false, true, 0, 0),
('Heliocare 360 Water Gel 50ml', 'IMPL-HELIO-WGE-50', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('KY Jelly', 'IMPL-KYJEL-STD', 'IMPLANT', 'tube', 375, true, true, 0, 0),
('PRP Kit', 'IMPL-PRP-KIT', 'IMPLANT', 'kit', 10000, true, true, 0, 0),
('Prilox Cream', 'IMPL-PRILO-STD', 'IMPLANT', 'tube', 0, false, true, 0, 0),
('Profhilo H & L', 'IMPL-PROFH-STD', 'IMPLANT', 'vial', 0, false, true, 0, 0),
('Semaglutide Pen (Ozempic)', 'IMPL-SEMA-PEN', 'IMPLANT', 'pen', 0, false, true, 0, 0),
('Viyata GFC Kit', 'IMPL-GFC-KIT', 'IMPLANT', 'kit', 0, false, true, 0, 0),
('Airway Guedel', 'AIR-GUED-STD', 'DISPOSABLE', 'piece', 435, true, true, 0, 0),
('Bacterial Filter (HME)', 'AIR-FILT-HME', 'DISPOSABLE', 'piece', 870, true, true, 0, 0),
('Breathing Filter (HMEF) Adult', 'AIR-FILT-HMEF', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Catheter Mount', 'AIR-CATH-MNT', 'DISPOSABLE', 'piece', 870, true, true, 0, 0),
('Endotracheal Tube Cuffed 6.5', 'AIR-ETT-CUFF-65', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Endotracheal Tube Cuffed 7', 'AIR-ETT-CUFF-7', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Endotracheal Tube Plain 4.5', 'AIR-ETT-PLAIN-45', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('LMA (Laryngeal Mask Airway)', 'AIR-LMA-STD', 'DISPOSABLE', 'piece', 440, true, true, 0, 0),
('Laryngeal Airway', 'AIR-LARYN-STD', 'DISPOSABLE', 'piece', 7000, true, true, 0, 0),
('Nasal Prongs', 'AIR-NASAL-PRNG', 'DISPOSABLE', 'piece', 300, true, true, 0, 0),
('Non-Rebreathing Mask Paediatric/Adult', 'AIR-MASK-NRB', 'DISPOSABLE', 'piece', 300, true, true, 0, 0),
('Suction Catheter Size 10', 'AIR-SUCT-10', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Suction Catheter Size 12', 'AIR-SUCT-12', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Suction Catheter Size 16', 'AIR-SUCT-16', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Suction Catheter Size 18', 'AIR-SUCT-18', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Suction Catheter Size 6', 'AIR-SUCT-6', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Yankauer Handle', 'AIR-YANK-HDL', 'DISPOSABLE', 'piece', 600, true, true, 0, 0),
('Yankauer Tubing 3m', 'AIR-YANK-TUB-3M', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Actrapid 100IU 10ml (Human Insulin)', 'MED-ACTR-100IU', 'ANESTHETIC', 'vial', 1200, true, true, 0, 0),
('Atracurium Injection 10mg/ml/5ml', 'MED-ATRA-10MG', 'ANESTHETIC', 'vial', 650, true, true, 0, 0),
('Bupivacaine Plain Injection 5ml', 'MED-BUPI-5ML', 'ANESTHETIC', 'vial', 420, true, true, 0, 0),
('Ephedrine', 'MED-EPHED-STD', 'ANESTHETIC', 'vial', 300, true, true, 0, 0),
('Fentanyl Injection 100mcg/2ml', 'MED-FENT-100MCG', 'ANESTHETIC', 'pack', 290, true, true, 0, 0),
('Heavy Marcaine', 'MED-MARC-HVY', 'ANESTHETIC', 'vial', 1062, true, true, 0, 0),
('Isoflurane', 'MED-ISO-STD', 'ANESTHETIC', 'unit', 35, true, true, 0, 0),
('Ketamine Injection (India)', 'MED-KETA-IND', 'ANESTHETIC', 'vial', 420, true, true, 0, 0),
('Ketamine Injection (Rotex)', 'MED-KETA-RTX', 'ANESTHETIC', 'vial', 800, true, true, 0, 0),
('Lignocaine Injection 2% 30ml', 'MED-LIGNO-2-30ML', 'ANESTHETIC', 'vial', 100, true, true, 0, 0),
('Lignocaine with Adrenaline 30ml', 'MED-LIGNO-ADR-30ML', 'ANESTHETIC', 'vial', 150, true, true, 0, 0),
('Midazolam', 'MED-MIDAZ-STD', 'ANESTHETIC', 'vial', 450, true, true, 0, 0),
('Morphine Injection 10mg', 'MED-MORPH-10MG', 'ANESTHETIC', 'pack', 300, true, true, 0, 0),
('Naloxone 0.4mcg', 'MED-NALOX-04MCG', 'ANESTHETIC', 'pack', 1020, true, true, 0, 0),
('Neostigmine', 'MED-NEOS-STD', 'ANESTHETIC', 'vial', 120, true, true, 0, 0),
('Pethidine Injection 100mg/2ml', 'MED-PETH-100MG', 'ANESTHETIC', 'pack', 290, true, true, 0, 0),
('Propofol Injection 1% 20ml', 'MED-PROP-20ML', 'ANESTHETIC', 'vial', 380, true, true, 0, 0),
('Remifentanil 5mg', 'MED-REMI-5MG', 'ANESTHETIC', 'vial', 2572, true, true, 0, 0),
('Sevoflurane', 'MED-SEVO-STD', 'ANESTHETIC', 'unit', 100, true, true, 0, 0),
('Soda Lime 4.5kg', 'MED-SODA-4-5KG', 'ANESTHETIC', 'bag', 0, false, true, 0, 0),
('Suxamethonium Injection', 'MED-SUXA-STD', 'ANESTHETIC', 'vial', 200, true, true, 0, 0),
('Bed Liners / Underpads', 'BAND-BED-LINER', 'DISPOSABLE', 'piece', 225, true, true, 0, 0),
('Compression Stocking', 'BAND-COMP-STKG', 'DISPOSABLE', 'pair', 3800, true, true, 0, 0),
('Crepe Bandage 2 inch', 'BAND-CREPE-2IN', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Crepe Bandage 3 inch', 'BAND-CREPE-3IN', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Crepe Bandage 4 inch', 'BAND-CREPE-4IN', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Crepe Bandage 6 inch', 'BAND-CREPE-6IN', 'DISPOSABLE', 'piece', 120, true, true, 0, 0),
('Micropore Tape', 'BAND-TAPE-MICRO', 'DISPOSABLE', 'roll', 400, true, true, 0, 0),
('Orthoband 6 inch', 'BAND-ORTH-6IN', 'DISPOSABLE', 'piece', 320, true, true, 0, 0),
('Plaster of Paris', 'BAND-POP-STD', 'DISPOSABLE', 'piece', 750, true, true, 0, 0),
('Transpore Tape', 'BAND-TAPE-TRANS', 'DISPOSABLE', 'roll', 300, true, true, 0, 0),
('Velosoft 1m (thick)', 'BAND-VELO-1M-THICK', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Velosoft 1m (thin)', 'BAND-VELO-1M-THIN', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Velsoft 6 inch', 'BAND-VELO-6IN', 'DISPOSABLE', 'piece', 780, true, true, 0, 0),
('Foley Catheter', 'CATH-FOL-STD', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Nasogastric Tube Size 12', 'CATH-NGT-12', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Nasogastric Tube Size 14', 'CATH-NGT-14', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Nasogastric Tube Size 16', 'CATH-NGT-16', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Nasogastric Tube Size 18', 'CATH-NGT-18', 'DISPOSABLE', 'piece', 100, true, true, 0, 0),
('Urine Bag', 'CATH-URINE-BAG', 'DISPOSABLE', 'piece', 150, true, true, 0, 0),
('Vaginal Speculum', 'CATH-VAG-SPEC', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Glucometer with Strips & Lancets', 'DIAG-GLUCO-KIT', 'DISPOSABLE', 'kit', 800, true, true, 0, 0),
('Aquacel', 'DRESS-AQUA-STD', 'DRESSING', 'piece', 3870, true, true, 0, 0),
('Bactigrass 10cm x 10cm', 'DRESS-BACT-10-10', 'DRESSING', 'piece', 150, true, true, 0, 0),
('Bactigrass 10cm x 40cm', 'DRESS-BACT-10-40', 'DRESSING', 'piece', 210, true, true, 0, 0),
('Betadine Antiseptic 125ml', 'DRESS-BETA-125ML', 'DRESSING', 'bottle', 0, false, true, 0, 0),
('Dressing Pack (Sterile)', 'DRESS-PACK-STD', 'DRESSING', 'pack', 500, true, true, 0, 0),
('Hypodress 5x8', 'DRESS-HYPO-5-8', 'DRESSING', 'piece', 80, true, true, 0, 0),
('Leukomed 10cm x 25cm (50s)', 'DRESS-LEUK-10-25', 'DRESSING', 'box', 300, true, true, 0, 0),
('Leukomed 8cm x 15cm (50s)', 'DRESS-LEUK-8-15', 'DRESSING', 'box', 140, true, true, 0, 0),
('Leukomed T Plus 10cm x 25cm (50s)', 'DRESS-LEUKTP-10-25', 'DRESSING', 'box', 355, true, true, 0, 0),
('Leukomed T Plus 8cm x 15cm (50s)', 'DRESS-LEUKTP-8-15', 'DRESSING', 'box', 200, true, true, 0, 0),
('MEBO Herbal Ointment', 'DRESS-MEBO-STD', 'DRESSING', 'tube', 1940, true, true, 0, 0),
('Mupirzed Ointment', 'DRESS-MUPIR-STD', 'DRESSING', 'tube', 1200, true, true, 0, 0),
('Pads', 'DRESS-PADS-STD', 'DRESSING', 'piece', 100, true, true, 0, 0),
('Pynodine 10cm x 10cm', 'DRESS-PYN-10-10', 'DRESSING', 'piece', 100, true, true, 0, 0),
('Pynodine 10cm x 40cm', 'DRESS-PYN-10-40', 'DRESSING', 'piece', 300, true, true, 0, 0),
('Sterile Abdominal Packs', 'DRESS-ABD-STR', 'DRESSING', 'piece', 980, true, true, 0, 0),
('Zupricin Ointment', 'DRESS-ZUPR-STD', 'DRESSING', 'tube', 1660, true, true, 0, 0),
('Medical Oxygen 8.5m³', 'GAS-OXY-8-5M3', 'DISPOSABLE', 'cylinder', 20, true, true, 0, 0),
('Nitrous Gas 30kg', 'GAS-N2O-30KG', 'DISPOSABLE', 'cylinder', 0, false, true, 0, 0),
('Blood Giving Set', 'ACC-IV-BLOOD-SET', 'DISPOSABLE', 'piece', 120, true, true, 0, 0),
('Brannular G18 (100s)', 'ACC-CANN-G18-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Brannular G20 (100s)', 'ACC-CANN-G20-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Brannular G22 (100s)', 'ACC-CANN-G22-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Brannular G24 (100s)', 'ACC-CANN-G24-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Disposable Spinal Needle 22G', 'ACC-SPIN-22G', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Disposable Spinal Needle 25G', 'ACC-SPIN-25G', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('IV Giving Sets (50s)', 'ACC-IV-SET-50', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Insulin Syringes 1ml', 'ACC-SYR-INSU-1ML', 'DISPOSABLE', 'piece', 30, true, true, 0, 0),
('Mindray Benetusion USP Syringe Pump', 'ACC-PUMP-MINDRAY', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Needle G18 (100s)', 'ACC-NDL-G18-100', 'DISPOSABLE', 'box', 10, true, true, 0, 0),
('Needle G21 (100s)', 'ACC-NDL-G21-100', 'DISPOSABLE', 'box', 10, true, true, 0, 0),
('Needle G23 (100s)', 'ACC-NDL-G23-100', 'DISPOSABLE', 'box', 10, true, true, 0, 0),
('Needle G25 (100s)', 'ACC-NDL-G25-100', 'DISPOSABLE', 'box', 10, true, true, 0, 0),
('Scalp Vein G21 (100s)', 'ACC-SCALP-G21-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Scalp Vein G23 (100s)', 'ACC-SCALP-G23-100', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Sonoplex 21G 10mm with Inj Tube', 'ACC-SONO-21G', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Syringe 60cc Luer Lock', 'ACC-SYR-60CC', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Syringes 10cc (100s)', 'ACC-SYR-10CC-100', 'DISPOSABLE', 'box', 20, true, true, 0, 0),
('Syringes 20cc (50s)', 'ACC-SYR-20CC-50', 'DISPOSABLE', 'box', 30, true, true, 0, 0),
('Syringes 2cc (100s)', 'ACC-SYR-2CC-100', 'DISPOSABLE', 'box', 20, true, true, 0, 0),
('Syringes 5cc (100s)', 'ACC-SYR-5CC-100', 'DISPOSABLE', 'box', 20, true, true, 0, 0),
('Dextrose 10% 500ml', 'FLU-D10-500ML', 'DISPOSABLE', 'bag', 140, true, true, 0, 0),
('Dextrose 50% 100ml', 'FLU-D50-100ML', 'DISPOSABLE', 'bag', 180, true, true, 0, 0),
('Dextrose Normal Saline (DNS) 500ml', 'FLU-DNS-500ML', 'DISPOSABLE', 'bag', 140, true, true, 0, 0),
('Mannitol 20% IV 500ml', 'FLU-MANN-20-500ML', 'DISPOSABLE', 'bag', 1600, true, true, 0, 0),
('Normal Saline 500ml', 'FLU-NS-500ML', 'DISPOSABLE', 'bag', 140, true, true, 0, 0),
('Ringers Lactate / Hartmanns 500ml', 'FLU-RL-500ML', 'DISPOSABLE', 'bag', 140, true, true, 0, 0),
('Acupan', 'MED-ACUP-STD', 'MEDICATION', 'vial', 600, true, true, 0, 0),
('Adrenaline Injection 1ml', 'MED-ADREN-1ML', 'MEDICATION', 'vial', 50, true, true, 0, 0),
('Atropine Injection 1ml', 'MED-ATRO-1ML', 'MEDICATION', 'vial', 50, true, true, 0, 0),
('Calcium Gluconate Injection 10ml', 'MED-CALC-10ML', 'MEDICATION', 'vial', 140, true, true, 0, 0),
('Cefuroxime Injection 750mg', 'MED-CEFU-750MG', 'MEDICATION', 'vial', 460, true, true, 0, 0),
('Clexane Injection', 'MED-CLEX-STD', 'MEDICATION', 'vial', 4700, true, true, 0, 0),
('Dexamethasone Injection 4mg/1ml', 'MED-DEX-4MG', 'MEDICATION', 'vial', 100, true, true, 0, 0),
('Diclofenac Injection 75mg/3ml', 'MED-DICL-75MG', 'MEDICATION', 'vial', 240, true, true, 0, 0),
('Esomeprazole Injection 40mg', 'MED-ESOME-40MG', 'MEDICATION', 'vial', 560, true, true, 0, 0),
('Flagyl (Metronidazole)', 'MED-FLAGY-STD', 'MEDICATION', 'vial', 300, true, true, 0, 0),
('Formaline Solution 5L', 'MED-FORM-5L', 'MEDICATION', 'bottle', 100, true, true, 0, 0),
('Gentamycin Injection 80mg/2ml', 'MED-GENTA-80MG', 'MEDICATION', 'vial', 36, true, true, 0, 0),
('Haemacel', 'MED-HAEM-STD', 'MEDICATION', 'bottle', 1300, true, true, 0, 0),
('Haloperidol', 'MED-HALO-STD', 'MEDICATION', 'vial', 200, true, true, 0, 0),
('Heparin Sodium 5000IU/ml', 'MED-HEPA-5000IU', 'MEDICATION', 'vial', 1350, true, true, 0, 0),
('Hyaluronidase', 'MED-HYALU-STD', 'MEDICATION', 'vial', 0, false, true, 0, 0),
('Hydrocortisone Injection', 'MED-HYDRO-STD', 'MEDICATION', 'vial', 140, true, true, 0, 0),
('Ketesse Injection 50mg', 'MED-KETE-50MG', 'MEDICATION', 'vial', 415, true, true, 0, 0),
('Lasix 20mg', 'MED-LASIX-20MG', 'MEDICATION', 'vial', 350, true, true, 0, 0),
('Magnesium Sulphate 50% IV 10ml', 'MED-MGS-50-10ML', 'MEDICATION', 'vial', 260, true, true, 0, 0),
('Metoclopramide Injection 1ml', 'MED-METO-1ML', 'MEDICATION', 'vial', 50, true, true, 0, 0),
('Ondansetron Injection 4ml', 'MED-ONDA-4ML', 'MEDICATION', 'vial', 975, true, true, 0, 0),
('Paracetamol IV 100ml', 'MED-PARA-IV-100ML', 'MEDICATION', 'bottle', 300, true, true, 0, 0),
('Piriton / Chlorphenamine', 'MED-PIRI-STD', 'MEDICATION', 'vial', 100, true, true, 0, 0),
('Potassium Chloride 1.5/10ml', 'MED-KCL-15-10ML', 'MEDICATION', 'vial', 170, true, true, 0, 0),
('Semaglutide 14mg', 'MED-SEMA-14MG', 'MEDICATION', 'unit', 0, false, true, 0, 0),
('Semaglutide Injection 4mg/3ml (Ozempic)', 'MED-SEMA-4MG', 'MEDICATION', 'pen', 0, false, true, 0, 0),
('Solumedrol Injection 500mg', 'MED-SOLUM-500MG', 'MEDICATION', 'vial', 0, false, true, 0, 0),
('Tramadol Injection 100mg/2ml', 'MED-TRAM-100MG', 'MEDICATION', 'pack', 435, true, true, 0, 0),
('Tranexamic Acid Injection 500mg', 'MED-TXA-500MG', 'MEDICATION', 'vial', 300, true, true, 0, 0),
('Triamcinolone / Triam Denk 40mg', 'MED-TRIAM-40MG', 'MEDICATION', 'vial', 1140, true, true, 0, 0),
('Voluven', 'MED-VOLU-STD', 'MEDICATION', 'bottle', 2000, true, true, 0, 0),
('Water for Injection 10ml', 'MED-WFI-10ML', 'MEDICATION', 'vial', 15, true, true, 0, 0),
('Dressing Fee Major', 'SVC-DRESS-MAJOR', 'OTHER', 'session', 1200, true, true, 0, 0),
('Dressing Fee Minor', 'SVC-DRESS-MINOR', 'OTHER', 'session', 550, true, true, 0, 0),
('Minor Theatre Fee (per 50 minutes)', 'SVC-THTR-50PM', 'OTHER', 'session', 0, false, true, 0, 0),
('Private Room + Nurse', 'SVC-ROOM-PRIV', 'OTHER', 'day', 15000, true, true, 0, 0),
('Staple Remover Use', 'SVC-STAP-RMV-USE', 'OTHER', 'session', 300, true, true, 0, 0),
('Theatre Fee (per 100 minutes)', 'SVC-THTR-100PM', 'OTHER', 'session', 0, false, true, 0, 0),
('Use of Sets', 'SVC-SETS-USE', 'OTHER', 'session', 700, true, true, 0, 0),
('Bin Liners Red 30x36 inch', 'STER-BIN-RED', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Bin Liners Yellow 30x36 inch', 'STER-BIN-YEL', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Cidex (Glutaraldehyde) 5L', 'STER-CIDEX-5L', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Endozyme 5L', 'STER-ENDOZ-5L', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Hand Paper Towels 12s Carton', 'STER-HAND-TOWEL', 'DISPOSABLE', 'carton', 0, false, true, 0, 0),
('Methylated Spirit 70% 5L', 'STER-METH-5L', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Nice & Soft Toilet Tissue (10s)', 'STER-NICE-TISSUE', 'DISPOSABLE', 'pack', 0, false, true, 0, 0),
('Rosy Bleach Regular 5L', 'STER-ROSY-BLEACH', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Rosy Handwash Pink 5L', 'STER-ROSY-HWASH', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Sharps Container 5L Cardboard', 'STER-SHRP-5L', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Velvex Multipurpose Detergent 5L', 'STER-VELV-DETG', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Velvex Toilet Cleaner 500ml', 'STER-VELV-TOILET', 'DISPOSABLE', 'bottle', 0, false, true, 0, 0),
('Velvex Toilet Tissue (10s)', 'STER-VELV-TISSUE', 'DISPOSABLE', 'pack', 0, false, true, 0, 0),
('Monocryl 2.0', 'SUTR-MONO-2-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Monocryl 3.0', 'SUTR-MONO-3-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Monocryl 4.0', 'SUTR-MONO-4-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Nylon 10/0 30cm', 'SUTR-NYL-10-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Nylon 2.0', 'SUTR-NYL-2-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Nylon 3.0', 'SUTR-NYL-3-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Nylon 4.0', 'SUTR-NYL-4-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Nylon 5.0', 'SUTR-NYL-5-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Nylon Loop 1', 'SUTR-NYL-LOOP-1', 'SUTURE', 'piece', 0, false, true, 0, 0),
('PDS Loop 1', 'SUTR-PDS-LOOP-1', 'SUTURE', 'piece', 1030, true, true, 0, 0),
('Prolene 2.0', 'SUTR-PROL-2-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Prolene 3.0', 'SUTR-PROL-3-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Prolene 4.0', 'SUTR-PROL-4-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Prolene 5.0', 'SUTR-PROL-5-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Skin Staples', 'SUTR-STAP-STD', 'SUTURE', 'piece', 1200, true, true, 0, 0),
('Staple Remover', 'SUTR-STAP-RMV', 'SUTURE', 'piece', 1500, true, true, 0, 0),
('Synthabs / Monocryl 3/0 90cm', 'SUTR-SYNTH-2-0', 'SUTURE', 'piece', 0, false, true, 0, 0),
('Vicryl 1', 'SUTR-VIC-1', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Vicryl 2', 'SUTR-VIC-2', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Vicryl 2.0', 'SUTR-VIC-2-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Vicryl 3.0', 'SUTR-VIC-3-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Vicryl 4.0', 'SUTR-VIC-4-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Vicryl 5.0', 'SUTR-VIC-5-0', 'SUTURE', 'piece', 400, true, true, 0, 0),
('Abdominal Packs', 'CON-ABD-PACK', 'DISPOSABLE', 'piece', 200, true, true, 0, 0),
('Autoclove Tape 1850', 'CON-AUTOCLV-TAPE', 'DISPOSABLE', 'roll', 0, false, true, 0, 0),
('Clean Gloves (box)', 'CON-GLOVE-CLN', 'DISPOSABLE', 'box', 1000, true, true, 0, 0),
('Diathermy Pencil', 'CON-DIATX-PENCIL', 'DISPOSABLE', 'piece', 350, true, true, 0, 0),
('Drain', 'CON-DRAIN-STD', 'DISPOSABLE', 'piece', 2100, true, true, 0, 0),
('EGG Electrodes ECG', 'CON-ECG-ELEC', 'DISPOSABLE', 'piece', 90, true, true, 0, 0),
('Flexoplate', 'CON-FLEX-PLATE', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Gammex Latex Surgical Gloves 7.5', 'CON-GLOVE-GAMX-75', 'DISPOSABLE', 'pair', 0, false, true, 0, 0),
('Gauze', 'CON-GAUZE-STD', 'DISPOSABLE', 'piece', 20, true, true, 0, 0),
('Gauze Roll 90cm x 90 yards', 'CON-GAUZE-ROLL', 'DISPOSABLE', 'roll', 0, false, true, 0, 0),
('Hepa Filter for Liposuction', 'CON-HEPA-LIPO', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Latex Powder Free Exam Gloves', 'CON-GLOVE-LATEX-PF', 'DISPOSABLE', 'box', 0, false, true, 0, 0),
('Lipo Flo Kit Set', 'CON-LIPO-FLO-KIT', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Nitrile Blue Exam Gloves Medium', 'CON-GLOVE-NIT-M', 'DISPOSABLE', 'box', 0, false, true, 0, 0),
('Shoe Covers (100s)', 'CON-SHOE-100S', 'DISPOSABLE', 'box', 100, true, true, 0, 0),
('Small Drapes', 'CON-DRAPE-SML', 'DISPOSABLE', 'piece', 700, true, true, 0, 0),
('Sterile Canister 250cc Filtron', 'CON-CANI-250CC', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Sterile Canister 500cc Filtron', 'CON-CANI-500CC', 'DISPOSABLE', 'piece', 0, false, true, 0, 0),
('Sterile Gloves', 'CON-GLOVE-STR', 'DISPOSABLE', 'pair', 200, true, true, 0, 0),
('Sterile Skin Marker with Ruler', 'CON-SKIN-MKR', 'DISPOSABLE', 'piece', 875, true, true, 0, 0),
('Surgical Blade G11', 'CON-BLADE-G11', 'DISPOSABLE', 'piece', 50, true, true, 0, 0),
('Surgical Blade G12', 'CON-BLADE-G12', 'DISPOSABLE', 'piece', 50, true, true, 0, 0),
('Surgical Blade G15', 'CON-BLADE-G15', 'DISPOSABLE', 'piece', 50, true, true, 0, 0),
('Surgical Blade G23', 'CON-BLADE-G23', 'DISPOSABLE', 'piece', 50, true, true, 0, 0),
('Surgical Gowns', 'CON-GOWN-STD', 'DISPOSABLE', 'piece', 800, true, true, 0, 0),
('Theatre Caps Disposable (100s)', 'CON-CAP-100S', 'DISPOSABLE', 'box', 50, true, true, 0, 0),
('Theatre Face Mask 3-Ply', 'CON-MASK-3PLY', 'DISPOSABLE', 'piece', 50, true, true, 0, 0),
('Universal Drape', 'CON-DRAPE-UNIV', 'DISPOSABLE', 'piece', 4000, true, true, 0, 0),
('Winner Reinforced Gown L', 'CON-GOWN-REINF-L', 'DISPOSABLE', 'piece', 0, false, true, 0, 0);

