-- Migration: Insert 225 inventory items into production
-- Source: nairobi_sculpt_clean_catalogue.xlsx

INSERT INTO "InventoryItem" (name, sku, category, unit_of_measure, unit_cost, is_active, is_billable, is_implant) VALUES
  ('Biretix Hydramat Gel 50ml', 'IMPL-BIRE-50ML', 'IMPLANT', 'tube', 0, true, false, false),
  ('Botox Per Unit', 'IMPL-BOTOX-UNIT', 'IMPLANT', 'unit', 450, true, true, true),
  ('Endocare Renewal Retinol 30ml', 'IMPL-ENDO-30ML', 'IMPLANT', 'tube', 0, true, false, false),
  ('Go Pain Arnica Gel 100g', 'IMPL-ARNICA-100G', 'IMPLANT', 'tube', 0, true, false, false),
  ('Heliocare 360 Gel Oil 50ml', 'IMPL-HELIO-GEL-50', 'IMPLANT', 'tube', 0, true, false, false),
  ('Heliocare 360 Invisible Spray 200ml', 'IMPL-HELIO-SPRY-200', 'IMPLANT', 'bottle', 0, true, false, false),
  ('Heliocare 360 Water Gel 50ml', 'IMPL-HELIO-WGE-50', 'IMPLANT', 'tube', 0, true, false, false),
  ('KY Jelly', 'IMPL-KYJEL-STD', 'IMPLANT', 'tube', 375, true, true, false),
  ('PRP Kit', 'IMPL-PRP-KIT', 'IMPLANT', 'kit', 10000, true, true, true),
  ('Prilox Cream', 'IMPL-PRILO-STD', 'IMPLANT', 'tube', 0, true, false, false),
  ('Profhilo H & L', 'IMPL-PROFH-STD', 'IMPLANT', 'vial', 0, true, false, true),
  ('Semaglutide Pen (Ozempic)', 'IMPL-SEMA-PEN', 'IMPLANT', 'pen', 0, true, false, true),
  ('Viyata GFC Kit', 'IMPL-GFC-KIT', 'IMPLANT', 'kit', 0, true, false, true),
  ('Airway Guedel', 'AIR-GUED-STD', 'DISPOSABLE', 'piece', 435, true, true, false),
  ('Bacterial Filter (HME)', 'AIR-FILT-HME', 'DISPOSABLE', 'piece', 870, true, true, false),
  ('Breathing Filter (HMEF) Adult', 'AIR-FILT-HMEF', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Catheter Mount', 'AIR-CATH-MNT', 'DISPOSABLE', 'piece', 870, true, true, false),
  ('Endotracheal Tube Cuffed 6.5', 'AIR-ETT-CUFF-65', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Endotracheal Tube Cuffed 7', 'AIR-ETT-CUFF-7', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Endotracheal Tube Plain 4.5', 'AIR-ETT-PLAIN-45', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('LMA (Laryngeal Mask Airway)', 'AIR-LMA-STD', 'DISPOSABLE', 'piece', 440, true, true, false),
  ('Laryngeal Airway', 'AIR-LARYN-STD', 'DISPOSABLE', 'piece', 7000, true, true, false),
  ('Nasal Prongs', 'AIR-NASAL-PRNG', 'DISPOSABLE', 'piece', 300, true, true, false),
  ('Non-Rebreathing Mask Paediatric/Adult', 'AIR-MASK-NRB', 'DISPOSABLE', 'piece', 300, true, true, false),
  ('Suction Catheter Size 10', 'AIR-SUCT-10', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Suction Catheter Size 12', 'AIR-SUCT-12', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Suction Catheter Size 16', 'AIR-SUCT-16', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Suction Catheter Size 18', 'AIR-SUCT-18', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Suction Catheter Size 6', 'AIR-SUCT-6', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Yankauer Handle', 'AIR-YANK-HDL', 'DISPOSABLE', 'piece', 600, true, true, false),
  ('Yankauer Tubing 3m', 'AIR-YANK-TUB-3M', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Actrapid 100IU 10ml (Human Insulin)', 'MED-ACTR-100IU', 'ANESTHETIC', 'vial', 1200, true, true, false),
  ('Atracurium Injection 10mg/ml/5ml', 'MED-ATRA-10MG', 'ANESTHETIC', 'vial', 650, true, true, false),
  ('Bupivacaine Plain Injection 5ml', 'MED-BUPI-5ML', 'ANESTHETIC', 'vial', 420, true, true, false),
  ('Ephedrine', 'MED-EPHED-STD', 'ANESTHETIC', 'vial', 300, true, true, false),
  ('Fentanyl Injection 100mcg/2ml', 'MED-FENT-100MCG', 'ANESTHETIC', 'pack', 290, true, true, false),
  ('Heavy Marcaine', 'MED-MARC-HVY', 'ANESTHETIC', 'vial', 1062, true, true, false),
  ('Isoflurane', 'MED-ISO-STD', 'ANESTHETIC', 'unit', 35, true, true, false),
  ('Ketamine Injection (India)', 'MED-KETA-IND', 'ANESTHETIC', 'vial', 420, true, true, false),
  ('Ketamine Injection (Rotex)', 'MED-KETA-RTX', 'ANESTHETIC', 'vial', 800, true, true, false),
  ('Lignocaine Injection 2% 30ml', 'MED-LIGNO-2-30ML', 'ANESTHETIC', 'vial', 100, true, true, false),
  ('Lignocaine with Adrenaline 30ml', 'MED-LIGNO-ADR-30ML', 'ANESTHETIC', 'vial', 150, true, true, false),
  ('Midazolam', 'MED-MIDAZ-STD', 'ANESTHETIC', 'vial', 450, true, true, false),
  ('Morphine Injection 10mg', 'MED-MORPH-10MG', 'ANESTHETIC', 'pack', 300, true, true, false),
  ('Naloxone 0.4mcg', 'MED-NALOX-04MCG', 'ANESTHETIC', 'pack', 1020, true, true, false),
  ('Neostigmine', 'MED-NEOS-STD', 'ANESTHETIC', 'vial', 120, true, true, false),
  ('Pethidine Injection 100mg/2ml', 'MED-PETH-100MG', 'ANESTHETIC', 'pack', 290, true, true, false),
  ('Propofol Injection 1% 20ml', 'MED-PROP-20ML', 'ANESTHETIC', 'vial', 380, true, true, false),
  ('Remifentanil 5mg', 'MED-REMI-5MG', 'ANESTHETIC', 'vial', 2572, true, true, false),
  ('Sevoflurane', 'MED-SEVO-STD', 'ANESTHETIC', 'unit', 100, true, true, false),
  ('Soda Lime 4.5kg', 'MED-SODA-4-5KG', 'ANESTHETIC', 'bag', 0, true, false, false),
  ('Suxamethonium Injection', 'MED-SUXA-STD', 'ANESTHETIC', 'vial', 200, true, true, false),
  ('Bed Liners / Underpads', 'BAND-BED-LINER', 'DRESSING', 'piece', 225, true, true, false),
  ('Compression Stocking', 'BAND-COMP-STKG', 'DRESSING', 'pair', 3800, true, true, false),
  ('Crepe Bandage 2 inch', 'BAND-CREPE-2IN', 'DRESSING', 'piece', 100, true, true, false),
  ('Crepe Bandage 3 inch', 'BAND-CREPE-3IN', 'DRESSING', 'piece', 100, true, true, false),
  ('Crepe Bandage 4 inch', 'BAND-CREPE-4IN', 'DRESSING', 'piece', 100, true, true, false),
  ('Crepe Bandage 6 inch', 'BAND-CREPE-6IN', 'DRESSING', 'piece', 120, true, true, false),
  ('Micropore Tape', 'BAND-TAPE-MICRO', 'DRESSING', 'roll', 400, true, true, false),
  ('Orthoband 6 inch', 'BAND-ORTH-6IN', 'DRESSING', 'piece', 320, true, true, false),
  ('Plaster of Paris', 'BAND-POP-STD', 'DRESSING', 'piece', 750, true, true, false),
  ('Transpore Tape', 'BAND-TAPE-TRANS', 'DRESSING', 'roll', 300, true, true, false),
  ('Velosoft 1m (thick)', 'BAND-VELO-1M-THICK', 'DRESSING', 'piece', 200, true, true, false),
  ('Velosoft 1m (thin)', 'BAND-VELO-1M-THIN', 'DRESSING', 'piece', 100, true, true, false),
  ('Velsoft 6 inch', 'BAND-VELO-6IN', 'DRESSING', 'piece', 780, true, true, false),
  ('Foley Catheter', 'CATH-FOL-STD', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Nasogastric Tube Size 12', 'CATH-NGT-12', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Nasogastric Tube Size 14', 'CATH-NGT-14', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Nasogastric Tube Size 16', 'CATH-NGT-16', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Nasogastric Tube Size 18', 'CATH-NGT-18', 'DISPOSABLE', 'piece', 100, true, true, false),
  ('Urine Bag', 'CATH-URINE-BAG', 'DISPOSABLE', 'piece', 150, true, true, false),
  ('Vaginal Speculum', 'CATH-VAG-SPEC', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Glucometer with Strips & Lancets', 'DIAG-GLUCO-KIT', 'DISPOSABLE', 'kit', 800, true, true, false),
  ('Aquacel', 'DRESS-AQUA-STD', 'DRESSING', 'piece', 3870, true, true, false),
  ('Bactigrass 10cm x 10cm', 'DRESS-BACT-10-10', 'DRESSING', 'piece', 150, true, true, false),
  ('Bactigrass 10cm x 40cm', 'DRESS-BACT-10-40', 'DRESSING', 'piece', 210, true, true, false),
  ('Betadine Antiseptic 125ml', 'DRESS-BETA-125ML', 'DRESSING', 'bottle', 0, true, false, false),
  ('Dressing Pack (Sterile)', 'DRESS-PACK-STD', 'DRESSING', 'pack', 500, true, true, false),
  ('Hypodress 5x8', 'DRESS-HYPO-5-8', 'DRESSING', 'piece', 80, true, true, false),
  ('Leukomed 10cm x 25cm (50s)', 'DRESS-LEUK-10-25', 'DRESSING', 'box', 300, true, true, false),
  ('Leukomed 8cm x 15cm (50s)', 'DRESS-LEUK-8-15', 'DRESSING', 'box', 140, true, true, false),
  ('Leukomed T Plus 10cm x 25cm (50s)', 'DRESS-LEUKTP-10-25', 'DRESSING', 'box', 355, true, true, false),
  ('Leukomed T Plus 8cm x 15cm (50s)', 'DRESS-LEUKTP-8-15', 'DRESSING', 'box', 200, true, true, false),
  ('MEBO Herbal Ointment', 'DRESS-MEBO-STD', 'DRESSING', 'tube', 1940, true, true, false),
  ('Mupirzed Ointment', 'DRESS-MUPIR-STD', 'DRESSING', 'tube', 1200, true, true, false),
  ('Pads', 'DRESS-PADS-STD', 'DRESSING', 'piece', 100, true, true, false),
  ('Pynodine 10cm x 10cm', 'DRESS-PYN-10-10', 'DRESSING', 'piece', 100, true, true, false),
  ('Pynodine 10cm x 40cm', 'DRESS-PYN-10-40', 'DRESSING', 'piece', 300, true, true, false),
  ('Sterile Abdominal Packs', 'DRESS-ABD-STR', 'DRESSING', 'piece', 980, true, true, false),
  ('Zupricin Ointment', 'DRESS-ZUPR-STD', 'DRESSING', 'tube', 1660, true, true, false),
  ('Medical Oxygen 8.5m³', 'GAS-OXY-8-5M3', 'ANESTHETIC', 'cylinder', 20, true, true, false),
  ('Nitrous Gas 30kg', 'GAS-N2O-30KG', 'ANESTHETIC', 'cylinder', 0, true, false, false),
  ('Blood Giving Set', 'ACC-IV-BLOOD-SET', 'DISPOSABLE', 'piece', 120, true, true, false),
  ('Brannular G18 (100s)', 'ACC-CANN-G18-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Brannular G20 (100s)', 'ACC-CANN-G20-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Brannular G22 (100s)', 'ACC-CANN-G22-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Brannular G24 (100s)', 'ACC-CANN-G24-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Disposable Spinal Needle 22G', 'ACC-SPIN-22G', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Disposable Spinal Needle 25G', 'ACC-SPIN-25G', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('IV Giving Sets (50s)', 'ACC-IV-SET-50', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Insulin Syringes 1ml', 'ACC-SYR-INSU-1ML', 'DISPOSABLE', 'piece', 30, true, true, false),
  ('Mindray Benetusion USP Syringe Pump', 'ACC-PUMP-MINDRAY', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Needle G18 (100s)', 'ACC-NDL-G18-100', 'DISPOSABLE', 'box', 10, true, true, false),
  ('Needle G21 (100s)', 'ACC-NDL-G21-100', 'DISPOSABLE', 'box', 10, true, true, false),
  ('Needle G23 (100s)', 'ACC-NDL-G23-100', 'DISPOSABLE', 'box', 10, true, true, false),
  ('Needle G25 (100s)', 'ACC-NDL-G25-100', 'DISPOSABLE', 'box', 10, true, true, false),
  ('Scalp Vein G21 (100s)', 'ACC-SCALP-G21-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Scalp Vein G23 (100s)', 'ACC-SCALP-G23-100', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Sonoplex 21G 10mm with Inj Tube', 'ACC-SONO-21G', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Syringe 60cc Luer Lock', 'ACC-SYR-60CC', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Syringes 10cc (100s)', 'ACC-SYR-10CC-100', 'DISPOSABLE', 'box', 20, true, true, false),
  ('Syringes 20cc (50s)', 'ACC-SYR-20CC-50', 'DISPOSABLE', 'box', 30, true, true, false),
  ('Syringes 2cc (100s)', 'ACC-SYR-2CC-100', 'DISPOSABLE', 'box', 20, true, true, false),
  ('Syringes 5cc (100s)', 'ACC-SYR-5CC-100', 'DISPOSABLE', 'box', 20, true, true, false),
  ('Dextrose 10% 500ml', 'FLU-D10-500ML', 'DISPOSABLE', 'bag', 140, true, true, false),
  ('Dextrose 50% 100ml', 'FLU-D50-100ML', 'DISPOSABLE', 'bag', 180, true, true, false),
  ('Dextrose Normal Saline (DNS) 500ml', 'FLU-DNS-500ML', 'DISPOSABLE', 'bag', 140, true, true, false),
  ('Mannitol 20% IV 500ml', 'FLU-MANN-20-500ML', 'DISPOSABLE', 'bag', 1600, true, true, false),
  ('Normal Saline 500ml', 'FLU-NS-500ML', 'DISPOSABLE', 'bag', 140, true, true, false),
  ('Ringers Lactate / Hartmanns 500ml', 'FLU-RL-500ML', 'DISPOSABLE', 'bag', 140, true, true, false),
  ('Acupan', 'MED-ACUP-STD', 'MEDICATION', 'vial', 600, true, true, false),
  ('Adrenaline Injection 1ml', 'MED-ADREN-1ML', 'MEDICATION', 'vial', 50, true, true, false),
  ('Atropine Injection 1ml', 'MED-ATRO-1ML', 'MEDICATION', 'vial', 50, true, true, false),
  ('Calcium Gluconate Injection 10ml', 'MED-CALC-10ML', 'MEDICATION', 'vial', 140, true, true, false),
  ('Cefuroxime Injection 750mg', 'MED-CEFU-750MG', 'MEDICATION', 'vial', 460, true, true, false),
  ('Clexane Injection', 'MED-CLEX-STD', 'MEDICATION', 'vial', 4700, true, true, false),
  ('Dexamethasone Injection 4mg/1ml', 'MED-DEX-4MG', 'MEDICATION', 'vial', 100, true, true, false),
  ('Diclofenac Injection 75mg/3ml', 'MED-DICL-75MG', 'MEDICATION', 'vial', 240, true, true, false),
  ('Esomeprazole Injection 40mg', 'MED-ESOME-40MG', 'MEDICATION', 'vial', 560, true, true, false),
  ('Flagyl (Metronidazole)', 'MED-FLAGY-STD', 'MEDICATION', 'vial', 300, true, true, false),
  ('Formaline Solution 5L', 'MED-FORM-5L', 'MEDICATION', 'bottle', 100, true, true, false),
  ('Gentamycin Injection 80mg/2ml', 'MED-GENTA-80MG', 'MEDICATION', 'vial', 36, true, true, false),
  ('Haemacel', 'MED-HAEM-STD', 'MEDICATION', 'bottle', 1300, true, true, false),
  ('Haloperidol', 'MED-HALO-STD', 'MEDICATION', 'vial', 200, true, true, false),
  ('Heparin Sodium 5000IU/ml', 'MED-HEPA-5000IU', 'MEDICATION', 'vial', 1350, true, true, false),
  ('Hyaluronidase', 'MED-HYALU-STD', 'MEDICATION', 'vial', 0, true, false, false),
  ('Hydrocortisone Injection', 'MED-HYDRO-STD', 'MEDICATION', 'vial', 140, true, true, false),
  ('Ketesse Injection 50mg', 'MED-KETE-50MG', 'MEDICATION', 'vial', 415, true, true, false),
  ('Lasix 20mg', 'MED-LASIX-20MG', 'MEDICATION', 'vial', 350, true, true, false),
  ('Magnesium Sulphate 50% IV 10ml', 'MED-MGS-50-10ML', 'MEDICATION', 'vial', 260, true, true, false),
  ('Metoclopramide Injection 1ml', 'MED-METO-1ML', 'MEDICATION', 'vial', 50, true, true, false),
  ('Ondansetron Injection 4ml', 'MED-ONDA-4ML', 'MEDICATION', 'vial', 975, true, true, false),
  ('Paracetamol IV 100ml', 'MED-PARA-IV-100ML', 'MEDICATION', 'bottle', 300, true, true, false),
  ('Piriton / Chlorphenamine', 'MED-PIRI-STD', 'MEDICATION', 'vial', 100, true, true, false),
  ('Potassium Chloride 1.5/10ml', 'MED-KCL-15-10ML', 'MEDICATION', 'vial', 170, true, true, false),
  ('Semaglutide 14mg', 'MED-SEMA-14MG', 'MEDICATION', 'unit', 0, true, false, false),
  ('Semaglutide Injection 4mg/3ml (Ozempic)', 'MED-SEMA-4MG', 'MEDICATION', 'pen', 0, true, false, false),
  ('Solumedrol Injection 500mg', 'MED-SOLUM-500MG', 'MEDICATION', 'vial', 0, true, false, false),
  ('Tramadol Injection 100mg/2ml', 'MED-TRAM-100MG', 'MEDICATION', 'pack', 435, true, true, false),
  ('Tranexamic Acid Injection 500mg', 'MED-TXA-500MG', 'MEDICATION', 'vial', 300, true, true, false),
  ('Triamcinolone / Triam Denk 40mg', 'MED-TRIAM-40MG', 'MEDICATION', 'vial', 1140, true, true, false),
  ('Voluven', 'MED-VOLU-STD', 'MEDICATION', 'bottle', 2000, true, true, false),
  ('Water for Injection 10ml', 'MED-WFI-10ML', 'MEDICATION', 'vial', 15, true, true, false),
  ('Dressing Fee Major', 'SVC-DRESS-MAJOR', 'OTHER', 'session', 1200, true, true, false),
  ('Dressing Fee Minor', 'SVC-DRESS-MINOR', 'OTHER', 'session', 550, true, true, false),
  ('Minor Theatre Fee (per 50 minutes)', 'SVC-THTR-50PM', 'OTHER', 'session', 0, true, false, false),
  ('Private Room + Nurse', 'SVC-ROOM-PRIV', 'OTHER', 'day', 15000, true, true, false),
  ('Staple Remover Use', 'SVC-STAP-RMV-USE', 'OTHER', 'session', 300, true, true, false),
  ('Theatre Fee (per 100 minutes)', 'SVC-THTR-100PM', 'OTHER', 'session', 0, true, false, false),
  ('Use of Sets', 'SVC-SETS-USE', 'OTHER', 'session', 700, true, true, false),
  ('Bin Liners Red 30x36 inch', 'STER-BIN-RED', 'INSTRUMENT', 'piece', 0, true, false, false),
  ('Bin Liners Yellow 30x36 inch', 'STER-BIN-YEL', 'INSTRUMENT', 'piece', 0, true, false, false),
  ('Cidex (Glutaraldehyde) 5L', 'STER-CIDEX-5L', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Endozyme 5L', 'STER-ENDOZ-5L', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Hand Paper Towels 12s Carton', 'STER-HAND-TOWEL', 'INSTRUMENT', 'carton', 0, true, false, false),
  ('Methylated Spirit 70% 5L', 'STER-METH-5L', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Nice & Soft Toilet Tissue (10s)', 'STER-NICE-TISSUE', 'INSTRUMENT', 'pack', 0, true, false, false),
  ('Rosy Bleach Regular 5L', 'STER-ROSY-BLEACH', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Rosy Handwash Pink 5L', 'STER-ROSY-HWASH', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Sharps Container 5L Cardboard', 'STER-SHRP-5L', 'INSTRUMENT', 'piece', 0, true, false, false),
  ('Velvex Multipurpose Detergent 5L', 'STER-VELV-DETG', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Velvex Toilet Cleaner 500ml', 'STER-VELV-TOILET', 'INSTRUMENT', 'bottle', 0, true, false, false),
  ('Velvex Toilet Tissue (10s)', 'STER-VELV-TISSUE', 'INSTRUMENT', 'pack', 0, true, false, false),
  ('Monocryl 2.0', 'SUTR-MONO-2-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Monocryl 3.0', 'SUTR-MONO-3-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Monocryl 4.0', 'SUTR-MONO-4-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Nylon 10/0 30cm', 'SUTR-NYL-10-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Nylon 2.0', 'SUTR-NYL-2-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Nylon 3.0', 'SUTR-NYL-3-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Nylon 4.0', 'SUTR-NYL-4-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Nylon 5.0', 'SUTR-NYL-5-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Nylon Loop 1', 'SUTR-NYL-LOOP-1', 'SUTURE', 'piece', 0, true, false, false),
  ('PDS Loop 1', 'SUTR-PDS-LOOP-1', 'SUTURE', 'piece', 1030, true, true, false),
  ('Prolene 2.0', 'SUTR-PROL-2-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Prolene 3.0', 'SUTR-PROL-3-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Prolene 4.0', 'SUTR-PROL-4-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Prolene 5.0', 'SUTR-PROL-5-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Skin Staples', 'SUTR-STAP-STD', 'SUTURE', 'piece', 1200, true, true, false),
  ('Staple Remover', 'SUTR-STAP-RMV', 'SUTURE', 'piece', 1500, true, true, false),
  ('Synthabs / Monocryl 3/0 90cm', 'SUTR-SYNTH-2-0', 'SUTURE', 'piece', 0, true, false, false),
  ('Vicryl 1', 'SUTR-VIC-1', 'SUTURE', 'piece', 400, true, true, false),
  ('Vicryl 2', 'SUTR-VIC-2', 'SUTURE', 'piece', 400, true, true, false),
  ('Vicryl 2.0', 'SUTR-VIC-2-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Vicryl 3.0', 'SUTR-VIC-3-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Vicryl 4.0', 'SUTR-VIC-4-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Vicryl 5.0', 'SUTR-VIC-5-0', 'SUTURE', 'piece', 400, true, true, false),
  ('Abdominal Packs', 'CON-ABD-PACK', 'DISPOSABLE', 'piece', 200, true, true, false),
  ('Autoclove Tape 1850', 'CON-AUTOCLV-TAPE', 'DISPOSABLE', 'roll', 0, true, false, false),
  ('Clean Gloves (box)', 'CON-GLOVE-CLN', 'DISPOSABLE', 'box', 1000, true, true, false),
  ('Diathermy Pencil', 'CON-DIATX-PENCIL', 'DISPOSABLE', 'piece', 350, true, true, false),
  ('Drain', 'CON-DRAIN-STD', 'DISPOSABLE', 'piece', 2100, true, true, false),
  ('ECG Electrodes ECG', 'CON-ECG-ELEC', 'DISPOSABLE', 'piece', 90, true, true, false),
  ('Flexoplate', 'CON-FLEX-PLATE', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Gammex Latex Surgical Gloves 7.5', 'CON-GLOVE-GAMX-75', 'DISPOSABLE', 'pair', 0, true, false, false),
  ('Gauze', 'CON-GAUZE-STD', 'DISPOSABLE', 'piece', 20, true, true, false),
  ('Gauze Roll 90cm x 90 yards', 'CON-GAUZE-ROLL', 'DISPOSABLE', 'roll', 0, true, false, false),
  ('Hepa Filter for Liposuction', 'CON-HEPA-LIPO', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Latex Powder Free Exam Gloves', 'CON-GLOVE-LATEX-PF', 'DISPOSABLE', 'box', 0, true, false, false),
  ('Lipo Flo Kit Set', 'CON-LIPO-FLO-KIT', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Nitrile Blue Exam Gloves Medium', 'CON-GLOVE-NIT-M', 'DISPOSABLE', 'box', 0, true, false, false),
  ('Shoe Covers (100s)', 'CON-SHOE-100S', 'DISPOSABLE', 'box', 100, true, true, false),
  ('Small Drapes', 'CON-DRAPE-SML', 'DISPOSABLE', 'piece', 700, true, true, false),
  ('Sterile Canister 250cc Filtron', 'CON-CANI-250CC', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Sterile Canister 500cc Filtron', 'CON-CANI-500CC', 'DISPOSABLE', 'piece', 0, true, false, false),
  ('Sterile Gloves', 'CON-GLOVE-STR', 'DISPOSABLE', 'pair', 200, true, true, false),
  ('Sterile Skin Marker with Ruler', 'CON-SKIN-MKR', 'DISPOSABLE', 'piece', 875, true, true, false),
  ('Surgical Blade G11', 'CON-BLADE-G11', 'DISPOSABLE', 'piece', 50, true, true, false),
  ('Surgical Blade G12', 'CON-BLADE-G12', 'DISPOSABLE', 'piece', 50, true, true, false),
  ('Surgical Blade G15', 'CON-BLADE-G15', 'DISPOSABLE', 'piece', 50, true, true, false),
  ('Surgical Blade G23', 'CON-BLADE-G23', 'DISPOSABLE', 'piece', 50, true, true, false),
  ('Surgical Gowns', 'CON-GOWN-STD', 'DISPOSABLE', 'piece', 800, true, true, false),
  ('Theatre Caps Disposable (100s)', 'CON-CAP-100S', 'DISPOSABLE', 'box', 50, true, true, false),
  ('Theatre Face Mask 3-Ply', 'CON-MASK-3PLY', 'DISPOSABLE', 'piece', 50, true, true, false),
  ('Universal Drape', 'CON-DRAPE-UNIV', 'DISPOSABLE', 'piece', 4000, true, true, false),
  ('Winner Reinforced Gown L', 'CON-GOWN-REINF-L', 'DISPOSABLE', 'piece', 0, true, false, false);